# These are supported funding model platforms

github: [effector]
patreon: zero_bias
open_collective: effector
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# custom: # Replace with a single custom sponsorship URL
