image: node:11

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

test_all:
  stage: test
  script:
    - yarn
    - yarn test-full
npm_next:
  stage: deploy
  script:
    - echo "publish npm next"
    - yarn
    - yarn test
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - yarn build:builder
    - node tools/builder.js publish next
  environment:
    name: npm
    url: https://www.npmjs.com/package/effector
  when: manual
  only:
    - master
# publish_next_to_npm:
#   stage: deploy
#   artifacts:
#     name: "$CI_COMMIT_TAG"
#     paths:
#       - npm/
#   script:
#     - yarn
#     - node tools/builder.js publish next
