image: node:11

cache:
  paths:
    - node_modules/

stages:
  - test
  # - deploy

test_all:
  stage: test
  script:
    - yarn
    - yarn test
# publish_next_to_npm:
#   stage: deploy
#   artifacts:
#     name: "$CI_COMMIT_TAG"
#     paths:
#       - npm/
#   script:
#     - yarn
#     - node tools/builder.js publish next
