version: "2.4"
services:
  web:
    build: .
    volumes:
      - "./src:/app/src"
    working_dir: /app
    mem_limit: 512M
    command: "npx parcel --no-cache --hmr-port 7011 --port 7010 src/index.html"
    ports:
      - "7010:7010"
      - "7011:7011"
