name: Add contributors
on:
  schedule:
    - cron:  '20 20 * * *'

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BobAnkh/add-contributors@v0.2.2
      with:
        CONTRIBUTOR: '## Contributors'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        COMMIT_MESSAGE: 'docs(README): update contributors'