name: effector publish

on:
  push:
    branches:
      - master
    paths:
      - packages/effector/package.json
      - packages/effector-react/package.json
      - packages/effector-vue/package.json
      - packages/bs-effector/package.json
      - packages/bs-effector-react/package.json
      - 'packages/@effector/babel-plugin/package.json'
      - 'packages/@effector/babel-plugin-react/package.json'
      - 'packages/@effector/forms/package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: 12
      - run: npm i -g yarn

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn build publish latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         version: 12
  #         registry-url: https://npm.pkg.github.com/
  #         scope: '@zerobias'
  #     - run: yarn
  #     - run: yarn build
  #     - run: cd npm/effector && npm config set registry 'https://npm.pkg.github.com/' && npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
