name: tests

on:
  push:
    paths:
      - 'packages/**'
      - 'src/**'
      - 'tasks/**'
      - 'tools/**'
      - 'babel.config.js'
      - 'jest.config.js'
      - 'package.json'
      - 'yarn.lock'
      - 'bsconfig.json'
jobs:
  common-tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node-12-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install deps
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - run: yarn test
        name: tests
  publish-github:
    needs: common-tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node-12-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install deps
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - run: yarn build
        name: build effector
      - name: set npm config
        run: npm config set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: configure for github registry
        run: node tools/versionHash
        env:
          VERSION_HASH_REGISTRY: https://npm.pkg.github.com/
      - name: publish effector on github
        run: cd npm/effector && npm publish
      - name: publish effector fallback
        if: failure()
        run: echo 'cannot publish effector to github'
      - name: publish effector-react on github
        run: cd npm/effector-react && npm publish
      - name: publish effector-react fallback
        if: failure()
        run: echo 'cannot publish effector-react to github'
